In [1]:
import numpy as np

x = np.random.uniform(0,1,size = 1000000)
x.mean()

0.49992183867645662

In [3]:
a = np.zeros(3)
a

array([ 0.,  0.,  0.])

In [5]:
a[0]
type(a[0])

numpy.float64

In [6]:
a = np.array((4,3,2,1))
a

array([4, 3, 2, 1])

In [8]:
a.sort()
a

array([1, 2, 3, 4])

In [12]:
a.sum()

10

In [13]:
a.mean()

2.5

In [14]:
a.max()

4

In [16]:
a.argmax()

3

In [18]:
a.cumsum()

array([ 1,  3,  6, 10], dtype=int32)

In [19]:
a.cumprod()

array([ 1,  2,  6, 24], dtype=int32)

In [20]:
a.var()

1.25

In [21]:
a.std()

1.1180339887498949

In [23]:
a.shape = (2,2)
a.T

array([[1, 3],
       [2, 4]])